### ISSUE TITLE
type-checking can fail silently when bundling

### ISSUE THREAD

**Issue by frankwallis** [frankwallis/plugin-typescript#107]
When plugin-typescript is configured to be the default transpiler, the ```bundle``` hook does not get called, which means that if there are missing files, type-checking can fail silently when bundling.

This issue does not happen when plugin-typescript is configured using ```packages``` configuration.

**Comment by frankwallis** [comment]
@guybedford - it looks like the plugin does not get added to the list of plugins when it is configured as the default transpiler, see [here](https://github.com/systemjs/builder/blob/master/lib/compile.js#L237). 

Should I raise this as an issue on systemjs/builder?

**Comment by guybedford** [comment]
@frankwallis transpilers do not currently support the bundle hook yes. Let's create a builder issue for this support.

**Comment by guybedford** [comment]
I've been putting some more thought to this and it's important to bear in mind that the ability to set a `System.transpiler` will be deprecated when ES modules are supported in all modern JS environments (a very long time, but a deprecation path none-the-less). Effectively, the transpiler field should only be considered as a way of supporting ES modules syntax published in other packages, and shouldn't actually be used to transpile other language features. Rather the plugin method should be the way of transpiling language features.

Supporting the bundle hook for the "transpiler" is thus not really on this (long) critical path. Rather, I think we should encourage the `loader: 'typescript'` approach here as the standard path, making it both the work-around and the standard convention.

I'd like to look rather at ensuring in jspm that the transpiler is configured as a local package `loader` then, so that we can avoid this. Let me know if that makes sense or if you have any questions here.

**Comment by guybedford** [comment]
This `loader` configuration will now be in the next beta release.

**Comment by frankwallis** [comment]
I'm happy to fit in with however you want it to work.  Are you saying that the ```packages``` will be automatically added to the config file or that the transpiler will be configured as a loader at runtime?

**Comment by guybedford** [comment]
By default the configuration now looks like on init:

```javascript
SystemJS.config({
  transpiler: "plugin-babel",
  packages: {
    "app": {
      "main": "app.js",
      "meta": {
        "*.js": {
          "loader": "plugin-babel"
        }
      }
    }
  }
```

So that the transpiler is set both as a loader and transpiler. This way, you get your type checking on the local app code, and normal ES6 module conversion on third-party code (which won't support the bundle hook).

**Comment by frankwallis** [comment]
I have updated the readme with instructions to configure the plugin as a loader when type-checking
