### ISSUE TITLE
Server Side Rendering React Example?

### ISSUE THREAD

**Issue by daslicht** [frankwallis/plugin-typescript#109]
How do we apply server side rendering for this example please?

https://github.com/frankwallis/plugin-typescript/tree/master/examples/react

**Comment by frankwallis** [comment]
You will need to put in a configurable http server like express so that you can intercept http requests, generate your html on the server and then inject it into index.html.

It is a bit beyond the scope of this project, so I suggest you find an example project such as this one: https://github.com/dfbaskin/react-server-side-es6-jspm/blob/master/server.js

**Comment by daslicht** [comment]
I am am ware of how to return rendered html , but how do you mount the app after html has been returned ?

**Comment by frankwallis** [comment]
You just render it into the same element where you injected the html on the server:

```ReactDOM.render(<Calculator />, document.getElementById('main'));```

Assuming you put the html into a div called 'main'

```
<body>
   <div id='main>
       <!-- Your server rendered html goes here -->
   </div>
</body>
```
