### ISSUE TITLE
Add support for tsconfig 'include' and 'exclude' globs.

### ISSUE THREAD

**Issue by aindlq** [frankwallis/plugin-typescript#149]
In typescript 2.0 it is possible to specify `include` and `exclude` parameters using globs like syntax, most of the time it is more convenient than `file` list.

For more details see `excludeDefinition` and `includeDefinition` in http://json.schemastore.org/tsconfig

**Comment by frankwallis** [comment]
I don't think this is possible because the plugin needs to support in-browser compilation. In the browser, the exact paths of all the files needs to be known so they can be requested over HTTP, and it is not possible to search the file system using wildcards. I'm going to close it, but I'm happy to continue the discussion..
