### ISSUE TITLE
Resolve typings automatically

### ISSUE THREAD

**Issue by Mosho1** [frankwallis/plugin-typescript#161]
It would be nice if typings from @types or the packages themselves could be resolved automatically. Is this something to be considered?

**Comment by frankwallis** [comment]
It's not really possible because, when loading in the browser, trying to load files which may or may not exist will cause 404 errors everywhere. I don't think even the typescript compiler automatically resolves @types packages, they have to be configured in the ```types``` compiler option.

**Comment by Mosho1** [comment]
I believe VSCode does, but yeah, easier with access to the file system. Closing this then, thanks for the reply.

**Comment by aluanhaddad** [comment]
@frankwallis TypeScript _does_ automatically resolve files from `node_modules/@types` the problem is that it is hard coded based on assumptions of the npm package layout and the Node require function.

@Mosho1 VS Code does nothing special here, it gets all of its information from the TypeScript language service.
