### ISSUE TITLE
Rollup error when using @types: A module cannot import itself

### ISSUE THREAD

**Issue by DorianGrey** [frankwallis/plugin-typescript#177]
Hi there,

we're currently trying to properly get rollup to work in our angular2-template (see the issue [here](https://github.com/flaviait/ng2-jspm-template/issues/43)). Since the recent update to plugin-typescript 5.2.9, the task seems to be started properly, but results in a somewhat curious error w.r.t. the usage of `@types`:
```
err  Error: A module cannot import itself (npm:@types/lodash@4.14.37/index.d.ts!github:frankwallis/plugin-typescript@5.2.9/plugin.js)
    at /home/linne/Projects/ng2-jspm-template/node_modules/rollup/dist/rollup.js:8915:13
```
I've already tried to versions of adoptions to `tsconfig.json`:
(1) - Both parts aiming at ES2015:
```
{
 ...
 "target": "es6",
 "module": "es2015",
  ...
}
```
(2) - Let only the module version aim at ES2015, but target at ES5:
```
{
 ...
 "target": "es5",
 "module": "es2015",
  ...
}
```
(We did not recognize this error earlier since we've just recently updated to a more recent beta of jspm-0.17 - before this update, the task passed without errors, but any effects as well.)
I'm not sure which part may cause this error - 
- the configuration?
- plugin-typescript?
- rollup?

Any ideas or thoughts?

€dit: Just for comparison, I've change the template to use the [typings](https://github.com/typings/typings) tool for external typings. This changed the resulting error, but still has something to do with typings processed by plugin-typescript:
```
err  Error: A module cannot import itself (npm:immutable@3.8.1/dist/immutable.d.ts!github:frankwallis/plugin-typescript@5.2.9/plugin.js)
    at /home/linne/Projects/ng2-jspm-template/node_modules/rollup/dist/rollup.js:8915:13
```
The typings for immutable.js are distributed with the package itself.

**Comment by frankwallis** [comment]
Thanks for raising this I have released a fix in 5.3.1. It was caused by the typings for lodash and immutable containing ambient declarations of subpackages and this was causing the plugin to list the files as dependencies of themselves.

The typings are slightly strange as I would expect them to be external typings not ambient typings, but I don't fully understand how this gets handled by typescript. I notice that you have the typings for immutable pointed to ```dist/immutable.d.ts``` I think this would probably be better off using ```dist/immutable-nonambient.d.ts```.
