### ISSUE TITLE
"source-map-support.js 404 (Not Found)"

### ISSUE THREAD

**Issue by jordymeow** [frankwallis/plugin-typescript#178]
Hello,

I am not sure it's really related to plugin-typescript but it always happen when I am trying to load my files through the typescript loader. My code is available here: https://github.com/jordymeow/meowbs-2016. I get this error in the Chrome console when I run this project. Do you have any idea what's happening?

**Comment by aluanhaddad** [comment]
I ran into this also. You can resolve the issue by running `jspm i --dev npm:source-map-support`.

I'm not sure what the right way to go about fixing the problem is because it's not listed as a dependency in TypeScript's package.json but from looking at the source code, the compiler is requiring it in a try block that conditionality doesn't work in the browser environment where it results in a 404.

This was introduced at some point during development of 2.1

The simplest solution is probably to modify the override in the jspm registry. 

@frankwallis what do you think?

**Comment by jordymeow** [comment]
Thank you @aluanhaddad, indeed it works fine. Would be great to know why we need to install it, and why it's not listed as a dependency.

**Comment by aluanhaddad** [comment]
I think the reason that it's not listed as a dependency is that it is intended to be optional. The way that optionality is handled is via a try catch block around what is assumed to be a synchronous require.

From my limited understanding, I don't think
that is really something SystemJS and jspm can reasonably be expected to detect and even if they good, the only thing that could preserve the behavior would be a non-trivial source transform.

I could be completely wrong and the issue could instead be related to other dependencies that are deliberately omitted from TypeScript via the jspm registry override.

@guybedford is my interpretation correct or is there a known way that jspm has for handling this scenario?

**Comment by aluanhaddad** [comment]
This should fix the issue temporarily https://github.com/jspm/registry/pull/997

**Comment by aluanhaddad** [comment]
@jordymeow This should be fixed now.

**Comment by jordymeow** [comment]
@aluanhaddad I will test it tomorrow, thanks a lot :)
