### ISSUE TITLE
Future of this plugin

### ISSUE THREAD

**Issue by guybedford** [frankwallis/plugin-typescript#18]
@frankwallis Traceur Babel and TypeScript all represent supersets of ES6, and as such it makes complete sense to treat TypeScript equally.

Please don't let TypeScript being merged as a transpiler stop development of this plugin though - it is not a portable way to distribute TypeScript by calling it `format: 'es6'` in a package.json at all. Transpiler options are not portable as the assumption is made of one ES.

As such, even with TypeScript in core, using a TypeScript plugin will be a far better way to load and share TypeScript code through jspm and SystemJS. In addition proper handling of definitions etc should also be part of plugin code and not something in SystemJS or ES6 Module Loader.

Ultimately the mid-term plan is to turn all transpilers into plugins, and finally separate the "language" from the "module format". This will provide a few benefits including allowing ES6 script transpilation as well as providing a graceful transition into true ES6 environments when ES6 modules can be treated a true "compile-to" format.

That is, in future this plugin will be the only way to load TypeScript in jspm. I'm working on getting there as soon as possible, but lining things up is getting harder these days. Just let me know if you have any questions on this at all.

**Comment by frankwallis** [comment]
Thanks for this, that clarifies things - I do have some questions and a few general points to make:

The 'System.register' output is now in TypeScript master but is not part of the latest release (1.5.0-beta), hopefully it will get released soon. I have had a play around with the code from master to see how it integrates and there are a couple of issues:

TypeScript itself is now incorrectly detected as being in System.register format, because it contains the string 'System.register'. This can be fixed quite easily with an override, or perhaps the format detection could be improved.

The main conflict between SystemJS and TypeScript at the moment is the .ts file extension. Currently plugin-typescript post-processes the compiled JavaScript and adds a '.ts!' extension to all the relative import paths, so that they get resolved correctly and automatically fed through the plugin. This works ok, but it is less than ideal and does cause some issues. A little while ago you mentioned that the logic for determining the default file extension for an imported file is going to change ([here](https://github.com/systemjs/systemjs/issues/319)), and also that it will be possible to specify plugins by file extension. I think that these 2 changes should solve a lot of issues for me, do you think they will be released soon?

There  are some features of the TypeScript language which cannot be used with single-file compilation (const enums, namespaces) - just something to be aware of. I think the compiler will spit out an appropriate error message if they are used in single-file mode.

What's the plan for making TypeScript a core option? Like I said I am happy to help out - even if it's just by doing some testing.

**Comment by frankwallis** [comment]
Ok I have seen the PRs now, that's awesome. I will try compiling my programs and see how I get on.

**Comment by guybedford** [comment]
Thanks, really appreciate your feedback. TypeScript being detected as System.register is actually right - it's the format after transpilation. Having plugins via config is a priority right now - I'm working on getting this into SystemJS right now along with the TypeScript work, hopefully very soon.

**Comment by frankwallis** [comment]
What I mean is that the TypeScript compiler *itself* is being detected as System.register, but it definitely isn't. This is why it currently needs a shim:

```
    "overrides": {
      "github:Arnavion/typescript-github@master": {
        "format": "global",
        "shim": {
          "bin/typescript": {
            "exports": "ts"
          }
        }
      }
    }
```

I have updated my [app](https://github.com/frankwallis/tower/tree/angular2) to use the new versions from @vladima and the compilation is working nicely and everything is a lot faster.

**Comment by guybedford** [comment]
Ahh I see, right. Yes we may need to add an override to TypeScript to make
that work.

**Comment by frankwallis** [comment]
Version 2.0 of this plugin now supports single-file transpilation in the same way as the built-in TypeScript transpiler. Users who are using Babel as he built-in transpiler will be able to use this plugin to compileTypeScript. 

Optionally the plugin can also type-check the code although this takes a little longer. I am working on a configuration which will enable a 'flow-like' experience using systemjs-builder in-memory builds to incrementally recompile changed files and their dependencies.
