### ISSUE TITLE
Typescript nightly builds

### ISSUE THREAD

**Issue by j-walker23** [frankwallis/plugin-typescript#48]
Hey, first I can't say thank you enough for this plugin. I am new to typescript and jspm/system and this would have been a sad experience if it wasn't for your time! Thank you.

This is a question on typescript versions. I am building a new api and a lot of the code from TS 1.7 will help. The milestone on github is at 100% so it seems like it won't be to long until they release it so i wanted to build against it now.

Using `ntypescript` the nightly builds i can do my dev just fine. Is it possible to make this plugin use that as well? Even if its a hack i do locally i don't care. Anything to get me by until they release 1.7.

**Comment by frankwallis** [comment]
Thanks, I'm glad you like it!

You can override the version of typescript used by this plugin by specifying an ```overrides``` entry in the jspm section of your package.json:

```
    "devDependencies": {
      "css": "systemjs/plugin-css@0.1.10",
      "ts": "frankwallis/plugin-typescript@^2.1.1"
    },
    "overrides": {
      "github:frankwallis/plugin-typescript@2.1.1": {
        "dependencies": {
          "typescript": "npm:typescript@1.8.0-dev.20151021"
        }
      }
    }
```

Also the nightly builds are published on npm as dev versions (```npm view typescript```) so you can use them if you prefer. I just fixed an issue caused by the api changing between 1.6 and 1.7, so let me know if you find any issues.

**Comment by frankwallis** [comment]
Actually I think you will have to use typescript@1.7.0-dev.20151016 until 1.8 gets added to the jspm registry
