### ISSUE TITLE
AngularJS app broken after upgrading from 2.1.6 to 2.2.0

### ISSUE THREAD

**Issue by juergenzimmermann** [frankwallis/plugin-typescript#54]
My AngularJS app with the latest AngularJS is broken after I upgraded plugin-typescript from 2.1.6 to 2.2.0. I attach a screenshot from the Chrome console.
![plugin-typescript](https://cloud.githubusercontent.com/assets/734334/10944641/8ab4bda6-831a-11e5-8c2a-4b1cd3765dda.png)

**Comment by frankwallis** [comment]
It looks like some ES6 is not being transpiled. Have you made any changes to the systemjs config (specifically transpiler or loader extensions)?

**Comment by frankwallis** [comment]
I think this is probably caused by having the compiler option ```target``` set to ```es6```. It's kind of annoying because you want it set to ```es6``` in your editor so that you can use Promise and Map, but the output does need to be ```es5```. TypeScript uses the ```target``` setting to mean both the output and the runtime environment.

There are 3 ways I can think of to fix this:
1) Override ```target``` in System.typescriptOptions and set it to ```es5```. Plugin typescript will automatically use the es6 default lib as it knows that an es6 environment will be available at runtime.
2) In tsconfig set ```noLib: true``` and add a file reference to ```node_modules/typescript/lib.es6.d.ts```
3) I change the plugin to always output es5. I am kind of loathe to do this as some people may be using typescript with ```target: es6``` output and then piping into babel for transpilation. This enables the use of generator functions for example.

(1) sounds like the easiest option to me. I am going to update the example projects and docs to follow this approach.

**Comment by juergenzimmermann** [comment]
Using `"target": "es5"` inside typescriptOptions {...} in config.js results in the following error message (meanwhile the bootstrap.ts is refactored into app/app.ts). Using directly (without your plugin) the TypeScript transpiler, then my web app also works fine.
![plugin-typescript](https://cloud.githubusercontent.com/assets/734334/10994539/49cd3a58-8477-11e5-8580-63a8af7a105f.png)

**Comment by frankwallis** [comment]
I think this will be because ```module``` is set to ```commonjs```, if you set it to ```system``` then it should work. The plugin should probably handle this better.

**Comment by juergenzimmermann** [comment]
Thank you, Frank! Now it works fine. To summarize: I added these 2 lines to `typescriptOptions` in `config.js`
```
    "target": "es5",
    "module": "system",
```

**Comment by frankwallis** [comment]
Excellent, I will make a change in the next release to output a warning in this scenario I think. Thanks.
