### ISSUE TITLE
timeout when bootstrapping ExampleComponent

### ISSUE THREAD

**Issue by lee-tunnicliffe** [frankwallis/plugin-typescript#55]
I noticed the timeout to bootstrap ExampleComponent.

It's not required to run the development version but the bundled version fails without it. Do you know why?

**Comment by frankwallis** [comment]
I don't honestly know, and I haven't really looked into it. If I had to guess it would be because there is some part of the angular2 initialization process which is asynchronous and doesn't get a chance to run before bootstrap is called as the whole bundle is loaded synchronously. When loading dynamically there is a window for code to execute before bootstrap is called. Perhaps its some zonejs thing?

I would be interested to know what it is and if it happens all bundling systems or just systemjs. Angular2 is obviously still pre-release so there are a few things like this which I have just been putting up with for the time being, and I imagine they will get addressed in due course.

**Comment by lee-tunnicliffe** [comment]
Thanks for this fix. Makes sense now :/
