### ISSUE TITLE
How to create index.d.ts for my code?

### ISSUE THREAD

**Issue by unional** [frankwallis/plugin-typescript#73]
`tsc --declaration src/index.ts --module commonjs` wouldn't work because it doesn't know systemjs.

Is writing it by hand is the only way right now?

**Comment by frankwallis** [comment]
Even if it did work I don't think it would produce a single .d.ts file for your whole package (assuming your package is more than just this one file). To do that you need to use [dts-generator](https://github.com/SitePen/dts-generator) or handcraft them. Hopefully this may get fixed by [this issue](https://github.com/Microsoft/TypeScript/issues/4433)

It should still be possible to generate the individual declaration files using tsc, even if the project is giving type errors. Maybe try ```tsc --declaration src/index.ts --module commonjs --moduleResolution classic```? There is work being done to enable tsc to find the typings in jspm_packages (in the same way as it does currently in node_modules) and there is a related issue [here](https://github.com/Microsoft/TypeScript/issues/6012)

**Comment by unional** [comment]
Thanks. I just post a comment on the last link.  I agree that's what really needed.  I have added logic on jspm to package a typescript module as-is into the `jspm_packages`, so with the resolution logic, I don't really need to generate the declaration files.
