### ISSUE TITLE
noEmitOnError: true causes failure

### ISSUE THREAD

**Issue by imdaveho** [frankwallis/plugin-typescript#75]
Set up following the README, tsconfig with noEmitOnError: true, and example.ts of: ```console.log('hello world')``` throws this error in the console:

```
Uncaught (in promise) Error: Cannot read property 'match' of undefined
	Error loading http://localhost:5555/static/build/source/index.ts
    at p (http://localhost:5555/static/build/jspm_packages/system.js:5:2396)
    at http://localhost:5555/static/build/jspm_packages/system.js:5:4421
```

Any ideas? Thanks.
Here is my tsconfig.json:

```
{
    "compilerOptions": {
	"target": "ES5",
	"module": "commonjs",
	"noImplicitAny": true,
	"removeComments": true,
	"noEmitOnError": true,
	"emitDecoratorMetadata": true,
	"experimentalDecorators": true
    }
}
```

**Comment by frankwallis** [comment]
Thanks, there were a couple of issues here, using ```noEmitOnError``` with ```isolatedModules``` is an invalid combination of configuration options, but the plugin was not reporting any configuration errors returned when transpiling. I have made a change to report any errors and to override ```noEmitOnError``` to false when transpiling.

This should now be fixed in 2.4.4
