### ISSUE TITLE
Typings "ignored"

### ISSUE THREAD

**Issue by nillis** [frankwallis/plugin-typescript#85]
**Expected behaviour**

When typings are defined in tsconfig, the tsc from command line runs succesfully. No manual "/// <reference ..." needed in each individual file. 
When loading ts file with this plugin, no compile errors are emit as the typings are loaded in the tsconfig.

**Actual behaviour**

When typings are defined in tsconfig, the tsc from command line runs succesfully. No manual "/// <reference ..." needed in each individual file. **OK**
When loading ts file with this plugin, compile errors are emit. I need to manually add "/// <reference ..." to each individual file. **NOK**

If my situation is not clear of you need a detailed example, shoot! Happy to discuss.

**Comment by frankwallis** [comment]
This seems to be working in the example projects - perhaps you need to add ```tsconfig: true``` to ```typescriptOptions``` in config.js?

**Comment by nillis** [comment]
I tried it, but it doesn't work. I created a sample which reproduces this issue:
https://github.com/nillis/ignore-typings

**Comment by frankwallis** [comment]
The issue here is that you are using the ```exclude``` option in tsconfig.json, rather than listing the files to be compiled. plugin-typescript loads all the declaration files contained in the ```files``` array, but there is nothing listed there. This is just a constraint of being able to type-check in the browser, it's not possible to scan the project for files like tsc does.

You can either add the declaration files and other files to the ```files``` array, or add a ```/// reference``` to your index.ts, as discussed in the other thread.

**Comment by nillis** [comment]
Great, thanks for the proposed solutions! I think integrating a filesglob step which adds the files property to the tsconfig will be the best (semi) automated way to deal with this problem
