### ISSUE TITLE
const enums not being inlined

### ISSUE THREAD

**Issue by ximenean** [frankwallis/plugin-typescript#89]
Hi Frank,

Const enums aren't being inlined when bundling. I expect:

```typescript
declare module crm {
  const enum documentType {
    email = 0,
    unknown = 1
  }
}

var test = crm.documentType.email;
```

to be converted to:

```typescript
var test = 0 /* email */
```

but instead it isn't converted at all.

**Comment by frankwallis** [comment]
My crystal ball tells me you have recently upgraded plugin-typescript... 

Unfortunately const enums are not supported by typescript when performing single-file compilation with ```isolatedModules``` and that is what the plugin is using to transpile the files. Essentially it is because the value of the enum is not available to the transpiler, see [here](https://github.com/Microsoft/TypeScript/issues/5243). 

You will have to convert them into real enums and export them from your packages, rather than just defining them in the declaration files I'm afraid.

**Comment by ximenean** [comment]
Thanks Frank. It's like you have a sixth sense...
